### ISSUE TITLE
你好可以加个联系方式吗？～

### ISSUE THREAD

**Issue by gguan** [KittenYang/KYAnimatedPageControl#13]
你好我github关注你好久了～我们app在招ios主力开发不知道你有没有兴趣～我们app叫Like，是玩具手办社区，你可以在applestore搜索，不知道你有没有兴趣加入我们一起工作～我微信gguan54:)

**Comment by KittenYang** [comment]
issue里面不要发这种毫不相关的问题！！招人不是像你这么招的。很low你知道吗？
